const Bestsellproducts =[
      {
        id:1,
        img:"images/product-3.png",
        offer:"20% off",
        title:" 2020 Limited Release Le Rosé ",
        cate:"organic",
        oldprice:"39.00",
        price:"29.00",
        link:"/shop",
      },

      {
        id:2,
        img:"images/product-5.png",
        offer:"",
        title:" 2020 Limited Release Le Rosé ",
        cate:"organic",
        oldprice:"39.00",
        price:"29.00",
        link:"/shop",
      },
      {
        id:3,
        img:"images/product-7.png",
        offer:"20% off",
        title:" 2020 Limited Release Le Rosé ",
        cate:"organic",
        oldprice:"39.00",
        price:"29.00",
        link:"/shop",
      },

      {
        id:4,
        img:"images/product-8.png",
        offer:"",
        title:" 2020 Limited Release Le Rosé ",
        cate:"organic",
        oldprice:"39.00",
        price:"29.00",
        link:"/shop",
      },
      {
        id:5,
        img:"images/product-9.png",
        offer:"50% off",
        title:" 2020 Limited Release Le Rosé ",
        cate:"organic",
        oldprice:"39.00",
        price:"29.00",
        link:"/shop",
      },

      {
        id:6,
        img:"images/product-3.png",
        offer:"40% off",
        title:" 2020 Limited Release Le Rosé ",
        cate:"organic",
        oldprice:"39.00",
        price:"29.00",
        link:"/shop",
      },
      {
        id:7,
        img:"images/product-5.png",
        offer:"30% off",
        title:" 2020 Limited Release Le Rosé ",
        cate:"organic",
        oldprice:"39.00",
        price:"29.00",
        link:"/shop",
      },
      {
        id:8,
        img:"images/product-7.png",
        offer:"",
        title:" 2020 Limited Release Le Rosé ",
        cate:"organic",
        oldprice:"39.00",
        price:"29.00",
        link:"/shop",
      },
]

export default Bestsellproducts;